### PR TITLE
Add group command

### PR DESCRIPTION
**Pull request by willowisp01**
**Group:** Creates a group with people corresponding to the selected IDs. 

- Parameters: [gp/GROUP_NAME] [id/STUDENTID] ... (multiple IDs allowed) 
- Example: group gp/3 id/A0123456X id/A0123456H 

**Notes:**

- If some IDs are not found, then those who are found will be added to a group. Those who are not are shown in an error message. (example: The following IDs were not found (and not added to the group): A0183456H )
- For now, each person is assigned to only one group. We can discuss this if you'd like.

### CODE REVIEW

**Comment by ronnnnnnnnn** [comment]
Do you think you should write tests for GroupCommand?

**Comment by willowisp01** [comment]
> Do you think you should write tests for GroupCommand?

I've added some more relevant tests.

**Comment by Wongqingyee** [comment]
lgtm!

**Comment by willowisp01** [comment]
> lgtm!

Thanks! It would be great if you could help me merge the PR.

**Pull request merged**
