### PR TITLE
Remove Address

### PR DESCRIPTION
**Pull request by ronnnnnnnnn**

### CODE REVIEW

**Comment by ronnnnnnnnn** [comment]
Does the patch coverage refer to the number of lines covered by tests?

**Comment by ronnnnnnnnn** [comment]
Ok but the line that's missing tests is the hashcode.  Should I write a test for that?

**Review by JiaXinEu — COMMENTED** [review]
LGTM

**Comment by Wongqingyee** [comment]
There seems to be merge conflicts.

**Comment by ronnnnnnnnn** [comment]
Thanks for the notification, merge conflicts have been resolved. The lines which are not covered by tests are consistent with previous PRs, so there should be no issue even though the checks are failing. Anyway, please review the changes!

**Pull request merged**
